# fly.toml app configuration file generated for hi-freecell on 2023-10-29T19:18:57+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hi-freecell"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
